services:
  thesis_container_dev:
    image: ${DOCKER_REGISTRY}thesis_container_dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: turtlewizard
        ROS_DISTRO: humble
    container_name: thesis_container_dev
    network_mode: "host"
    environment:
      - DISPLAY=:0.0
      - MAKEFLAGS="-j6 -l6"
      - ROS_DOMAIN_ID=73
      - TURTLE_HOME_IP=100.85.120.127
      - GAZEBO_MASTER_URI=localhost:11345
      # - MIXINS
      # - CCACHE_DIR="/home/ubuntu/.cache/ccache"
    logging:
      driver: "journald"
    stdin_open: true
    tty: true
    stop_signal: SIGINT
    privileged: true
    volumes:
      - /dev:/dev
      - ./:/home/turtlewizard/thesis-mppi-model-ident
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gitconfig:/home/turtlewizard/.gitconfig
      - ~/.ssh:/home/turtlewizard/.ssh
      - /usr/share/gazebo-11/models:/usr/share/gazebo-11/models
    group_add:
      - plugdev

  thesis_container_dev2:
    image: ${DOCKER_REGISTRY}thesis_container_dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: turtlewizard
        ROS_DISTRO: humble
    container_name: thesis_container_dev2
    network_mode: "host"
    environment:
      - DISPLAY=:0.0
      - MAKEFLAGS="-j6 -l6"
      - ROS_DOMAIN_ID=72
      - TURTLE_HOME_IP=100.85.120.127
      - GAZEBO_MASTER_URI=localhost:11346
      # - MIXINS
      # - CCACHE_DIR="/home/ubuntu/.cache/ccache"
    logging:
      driver: "journald"
    stdin_open: true
    tty: true
    stop_signal: SIGINT
    privileged: true
    volumes:
      - /dev:/dev
      - ./:/home/turtlewizard/thesis-mppi-model-ident
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gitconfig:/home/turtlewizard/.gitconfig
      - ~/.ssh:/home/turtlewizard/.ssh
      - /usr/share/gazebo-11/models:/usr/share/gazebo-11/models
    group_add:
      - plugdev

  thesis_container_dev3:
    image: ${DOCKER_REGISTRY}thesis_container_dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: turtlewizard
        ROS_DISTRO: humble
    container_name: thesis_container_dev3
    network_mode: "host"
    environment:
      - DISPLAY=:0.0
      - MAKEFLAGS="-j6 -l6"
      - ROS_DOMAIN_ID=71
      - TURTLE_HOME_IP=100.85.120.127
      - GAZEBO_MASTER_URI=localhost:11347
      # - MIXINS
      # - CCACHE_DIR="/home/ubuntu/.cache/ccache"
    logging:
      driver: "journald"
    stdin_open: true
    tty: true
    stop_signal: SIGINT
    privileged: true
    volumes:
      - /dev:/dev
      - ./:/home/turtlewizard/thesis-mppi-model-ident
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gitconfig:/home/turtlewizard/.gitconfig
      - ~/.ssh:/home/turtlewizard/.ssh
      - /usr/share/gazebo-11/models:/usr/share/gazebo-11/models
    group_add:
      - plugdev

  # thesis_container_berry:
  #   image: ${DOCKER_REGISTRY}thesis_container_berry
  #   platform: linux/arm64/v8
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       USERNAME: turtlewizard
  #       ROS_DISTRO: humble
  #   container_name: thesis_container_berry
  #   network_mode: "host"
  #   environment:
  #     - DISPLAY
  #     - MAKEFLAGS="-j6 -l6"
  #     - ROS_DOMAIN_ID=73
  #     # - MIXINS
  #     # - CCACHE_DIR="/home/ubuntu/.cache/ccache"
  #   logging:
  #     driver: "journald"
  #   stdin_open: true
  #   tty: true
  #   stop_signal: SIGINT
  #   privileged: true
  #   volumes:
  #     - /dev:/dev
  #     - ./:/home/turtlewizard/thesis-mppi-model-ident
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ~/.gitconfig:/home/ubuntu/.gitconfig
  #     - ~/.ssh:/home/ubuntu/.ssh
  #   group_add:
  #     - plugdev

