output_dir: 'results'
test_mode: 0  # 0 means multiple plan, 1 means one plan
controller_runs: 5  # only when test_mode=1
number_of_goals: 2
min_distance: 3.0  # [m]
robot_length:  0.2  # along the x-axis of the robot [m]
robot_width: 0.2  # along the y-axis [m]
planner: 'GridBased'
controllers: ['MPPI_example', 'MPPI_Maneuver']
odom_topic: '/odom'
costmap_topic: '/local_costmap/costmap'