robot_name: turtlebot3_waffle
planner: GridBased
controller: FollowPathMPPI
# default_controller_params: config/controller_server_params_reformat/default_mppi_params_reformatted.yaml
cmd_vel_topic: /cmd_vel
odom_topic: /odom
costmap_topic: /local_costmap/costmap
mppi_critic_topic: /mppi_critic_scores
# maps: [corridor_empty, corridor_mid_obstacles, corridor_side_obstacles]
reference_map: complex_ref
maps: [complex, complex_ref, complex_test, turtlebot3]
complex:
  path: 'maps/complex.yaml'
  path_local: 'maps/complex_local.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 10.3
    y: 0.0
    yaw: 0.0
complex_ref:
  path: 'maps/complex.yaml'
  # path_local: 'maps/complex_local.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 10.3
    y: 0.0
    yaw: 0.0
complex_test:
  path: 'maps/complex.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 3.0
    y: 0.0
    yaw: 0.0
turtlebot3:
  path: 'maps/turtlebot3_world.yaml'
  start_pose:
    x: -2.0
    y: -0.5
    yaw: 0.0
  goal_pose:
    x: 0.65
    y: 1.0
    yaw: 1.57
corridor_empty:
  path: 'maps/corridor_empty.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 2.0
    y: 0.0
    yaw: 0.0
corridor_mid_obstacles:
  path: 'maps/corridor_mid_obstacles.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 2.0
    y: 0.0
    yaw: 0.0
  # goal_pose:
  #   x: 8.0
  #   y: 0.0
  #   yaw: 0.0
corridor_side_obstacles:
  path: 'maps/corridor_side_obstacles.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 2.0
    y: 0.0
    yaw: 0.0
corridor_mixed:
  path: 'maps/corridor_mixed.yaml'
  # path_local: 'maps/corridor_mixed_local.yaml'
  start_pose:
    x: 0.0
    y: 0.0
    yaw: 0.0
  goal_pose:
    x: 8.25
    y: 0.0
    yaw: 0.0
