trials:
  - test_trial
  - test_random
  - default_distribution
  - enjoy_distribution
  - enjoy_distribution_w_enjoy_params
  - burger_distribution
  - waffle_random
  - waffle_grid
  - waffle_bayesian
  - enjoy_random_small
  - enjoy_random
  - enjoy_grid
  - enjoy_bayesian
  - bayes_test
  - waffle_bayesian_big
  - enjoy_bayesian_big
  - waffle_bayes_f
  - waffle_bayes_time
  - waffle_bayes_jerk
test_trial:
  map: complex_ref
  robot: waffle
  generator: default
  score_method: default
  runs: 2
  run_timeout: 60
test_random:
  map: complex_test
  robot: waffle
  generator: random
  score_method: default
  runs: 5
  run_timeout: 60
default_distribution:  # ran on local default_distribution_2024-11-24_13-23-28
  map: complex_ref  # without local
  robot: waffle
  generator: default
  score_method: default
  runs: 100
  run_timeout: 60
enjoy_distribution:  # running in ws sim 0
  map: complex_ref
  robot: enjoy
  generator: default
  score_method: default
  runs: 100
  run_timeout: 60
enjoy_distribution_w_enjoy_params:
  map: complex_ref
  robot: enjoy
  generator: default
  score_method: default
  runs: 100
  run_timeout: 60
burger_distribution:  # running in ws sim 71
  map: complex_ref
  robot: burger
  generator: default
  score_method: default
  runs: 100
  run_timeout: 60
waffle_random:  # running in ws sim 72
  map: complex_ref
  robot: waffle
  generator: random
  score_method: default
  runs: 500
  run_timeout: 60
waffle_grid:  # running in ws sim 73
  map: complex_ref
  robot: waffle
  generator: grid
  score_method: default
  runs: 808
  run_timeout: 60
bayes_test:
  map: complex_ref
  robot: waffle
  generator: bayesian
  score_method: default
  runs: 10
  run_timeout: 60
waffle_bayesian:
  map: complex_ref
  robot: waffle
  generator: bayesian
  score_method: default
  runs: 100
  run_timeout: 60
waffle_bayesian_big:
  map: complex_ref
  robot: waffle
  generator: bayesian
  score_method: default
  runs: 500
  run_timeout: 60
enjoy_random_small:
  map: complex_ref
  robot: enjoy
  generator: random
  score_method: default
  runs: 100
  run_timeout: 60
enjoy_random:
  map: complex_ref
  robot: enjoy
  generator: random
  score_method: default
  runs: 500
  run_timeout: 60
enjoy_grid:
  map: complex_ref
  robot: enjoy
  generator: grid
  score_method: default
  runs: 808
  run_timeout: 60
enjoy_bayesian:
  map: complex_ref
  robot: enjoy
  generator: bayesian
  score_method: default
  runs: 100
  run_timeout: 60
enjoy_bayesian_big:
  map: complex_ref
  robot: enjoy
  generator: bayesian
  score_method: default
  runs: 500
  run_timeout: 60
waffle_bayes_f:
  map: complex_ref
  robot: waffle
  generator: bayesian
  score_method: frechet
  runs: 100
  run_timeout: 60
waffle_bayes_time:
  map: complex_ref
  robot: waffle
  generator: bayesian
  score_method: time
  runs: 100
  run_timeout: 60
waffle_bayes_jerk:
  map: complex_ref
  robot: waffle
  generator: bayesian
  score_method: jerk
  runs: 100
  run_timeout: 60