---
/controller_server:
  ros__parameters:
    controller_frequency: 20.0
    controller_plugins: [FollowPathDefault, FollowPathMPPI]
    failure_tolerance: 0.3
    general_goal_checker.plugin: nav2_controller::SimpleGoalChecker
    general_goal_checker.stateful: true
    general_goal_checker.xy_goal_tolerance: 0.25
    general_goal_checker.yaw_goal_tolerance: 0.25
    goal_checker_plugins: [general_goal_checker]
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    progress_checker.movement_time_allowance: 10.0
    progress_checker.plugin: nav2_controller::SimpleProgressChecker
    progress_checker.required_movement_radius: 0.5
    progress_checker_plugin: progress_checker
    use_sim_time: true
